import normal from '../../assets/web/mascot-normal.png';
import heureux from '../../assets/web/mascot-heureux.png';
import search from '../../assets/web/mascot-search.png';
import surpris from '../../assets/web/mascot-surpris.png';
import clin from '../../assets/web/mascot-clin.png';
import sleepy from '../../assets/web/mascot-sleepy.png';
import empty from '../../assets/web/mascot-empty.png';
import celebrate from '../../assets/web/mascot-celebrate.png';

/**
 * Canonical mascot variants. Sources live in assets/ and are never redrawn; assets/web/ holds the derived web images
 * (common frame, same body size, downsized), generated by tools/prepare-mascots.mjs.
 */
const SOURCES = { normal, heureux, search, surpris, clin, sleepy, empty, celebrate } as const;

export type MascotVariant = keyof typeof SOURCES;

type Props = {
  variant: MascotVariant;
  width: number;
  float?: boolean;
  className?: string;
  /** Decorative by default. */
  alt?: string;
};

export function Mascot({ variant, width, float = false, className, alt = '' }: Props) {
  const classes = [float ? 'mascot-float' : '', className ?? ''].filter(Boolean).join(' ');
  return <img src={SOURCES[variant]} alt={alt} width={width} className={classes || undefined} style={{ width }} draggable={false} />;
}
